# Generated by Django 4.0.2 on 2022-04-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='accounts.Amenity'),
        ),
    ]
