# Generated by Django 4.0.2 on 2022-05-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_users_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
