# Generated by Django 4.0.2 on 2022-06-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_amenity_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extra_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moth_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('month_extra_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
