# Generated by Django 4.0.2 on 2022-06-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='moth_price',
            new_name='month_price',
        ),
    ]
