# Generated by Django 3.2.5 on 2022-06-09 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_users_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewschool',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_school_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewoffice',
            name='review_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_office', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='reviewoffice',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_office_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewkindergarten',
            name='review_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cat_kindergarten', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='reviewkindergarten',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_kindergarten_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
